name: flovi_driver
description: Flovi driver app demo.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.5
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
